config/routes.rb
Rails.application.routes.draw do
  resources :books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
end

app/models/reader.rb
class Reader < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  respond_to :html
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :delete]
  def index
    @books = Book.all
  end

  def show
  end

  def edit
  end

  def update
    @book.update(book_params)
    respond_with(@book)
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.create(book_params)
    respond_with(@book)
  end

  def destroy
    respond_with(@book.destroy)
  end

  private

  def book_params
    params.require(:book).permit(:title, :number, :author)
  end

  def set_book
    @book = Book.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.slim
tr
  td=
  td= link_to book.title, book_path(book)
  td= book.author
  td= book.number

app/views/books/_form.html.slim
= form_for book do |f|
  = render 'common/errors', resource: book
  .form-group
    = f.label :title, 'Наименование'
    = f.text_field :title, class: 'form-control'
  .form-group
    = f.label :author, 'Автор'
    = f.text_field :author, class: 'form-control'
  .form-group
    = f.label :number,  'Инвентарный номер'
    = f.text_field :number, class: 'form-control'
  .form-group
    = f.submit 'Сохранить', class: 'btn btn-primary'

app/views/books/edit.html.slim
= render 'form', book: @book

app/views/books/index.html.slim
/ = will_paginate @books
table.table.table-bordered.table-hover
  thead
    tr
      th №
      th Наименование
      th Автор
      th Инвентарный номер
  tbody
    = render @books, index: @index
p = link_to 'Добавить книгу', new_book_path, class: 'btn btn-primary'

app/views/books/new.html.slim
= render 'form', book: @book

app/views/books/show.html.slim
.well.book
  p Наименование: #{@book.title}
  p Автор: #{@book.author}
  p Инвентарный номер: #{@book.number}
= link_to 'Изменить', edit_book_path(@book), class: 'btn btn-primary'
'
= link_to 'Удалить', @book, method: :delete, class: 'btn btn-primary'

app/views/common/_errors.html.slim
- if resource.errors.any?
    ul
    - resource.errors.full_messages.each do |error|
      li= error

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= content_for?(:title) ? yield(:title) : "Library"
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"
    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js"


  body
    .navbar.navbar-default.navbar-static-top
        .container
          button.navbar-toggle type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse"
            span.icon-bar
            span.icon-bar
            span.icon-bar
          a.navbar-brand href="#"Library
          .navbar-collapse.collapse.navbar-responsive-collapse
            ul.nav.navbar-nav
              li= link_to "Книги", books_path
              li= link_to "Link 2", "/path2"
              li= link_to "Link 3", "/path3"

    .container
      .row
        .col-lg-9
          = bootstrap_flash
          = yield
        .col-lg-3
          .well.sidebar-nav
            h3 Sidebar
            ul.nav.nav-list
              li.nav-header Sidebar
              li= link_to "Link 1", "/path1"
              li= link_to "Link 2", "/path2"
              li= link_to "Link 3", "/path3"

      footer
        p &copy; Company 2017